/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventType = IDL.Variant({
  'seminar' : IDL.Null,
  'workshop' : IDL.Null,
  'competition' : IDL.Null,
});
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'numberOfMembers' : IDL.Nat,
  'collegeName' : IDL.Text,
  'year' : IDL.Nat,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'paymentScreenshotFileName' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'eventType' : EventType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Stats = IDL.Record({
  'totalMembers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalRegistrations' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRegistration' : IDL.Func([IDL.Nat], [IDL.Opt(Registration)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        EventType,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventType = IDL.Variant({
    'seminar' : IDL.Null,
    'workshop' : IDL.Null,
    'competition' : IDL.Null,
  });
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'numberOfMembers' : IDL.Nat,
    'collegeName' : IDL.Text,
    'year' : IDL.Nat,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'paymentScreenshotFileName' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'eventType' : EventType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Stats = IDL.Record({
    'totalMembers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalRegistrations' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRegistration' : IDL.Func([IDL.Nat], [IDL.Opt(Registration)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          EventType,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };